api/urls.py
from django.urls import include, path
from rest_framework import routers
from api import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'products', views.ProductViewSet)

urlpatterns = [
    path('',include(router.urls)),
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # path('product/', views.product_api),
]

myapp/urls.py
# from turtle import update
from django.urls import path,include
from .views import ProductDelete,  ProductDetailView,ProductListView,ProductUpdateView ,index , new_one, product_details, products,add_product, update_product,delete_product

from . import views

app_name = 'myapp'

urlpatterns = [
    path('',index),
    path('new/',new_one),
    # path('products/', products,name='products'),
    path('products/',ProductListView.as_view(),name = 'products'),
    # path('products/<int:id>',product_details,name='product_details'),
    path('products/<int:pk>',ProductDetailView.as_view(),name = 'product_details'),
    path('products/add',add_product,name='add_product'),
    # path('products/update/<int:id>',update_product,name='update_product'),
    path('products/update/<int:pk>',ProductUpdateView.as_view(),name = 'update_product'),     
    # path('products/delete/<int:id>',delete_product,name='delete_product'),
    path('products/delete/<int:pk>',ProductDelete.as_view(),name = 'delete_product'),
#addtocart
    path('add_to_cart/',views.add_to_cart,name='add_to_cart'),
    # path('cart/',views.show_cart,name='showcart')
] 

mysite/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path,include
# from  myapp.views import index,new_one
from django.conf.urls.static import static

from mysite import settings

from myapp import views



urlpatterns = [
    path('admin/', admin.site.urls),
  
    
]
urlpatterns += [
    path('myapp/',include('myapp.urls')),
    path('users/',include('users.urls')),
    path('api/',include('api.urls')),
    path("__reload__/", include("django_browser_reload.urls")),

       

]

urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)

users/urls.py
from tempfile import template
from turtle import update
from django.urls import path,include
from .views import register,profile,create_profile,seller_profile
from django.contrib.auth import views as authentication_views

app_name = 'users'

urlpatterns = [
  
    path('register/', register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',profile,name='profile'),
    path('createprofile/',create_profile,name='createprofile'),
    path('sellerprofile/<int:id>',seller_profile,name='sellerprofile'),
]

myapp/models.py
from distutils.command.upload import upload
from email.mime import image
from enum import unique
from pickle import TRUE
from unicodedata import name
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Product(models.Model):
    def __str__(self):
        return self.name
    name = models.CharField(max_length =100,unique=True)
    price = models.FloatField()
    description = models.CharField(max_length =200)
    image=models.ImageField(blank=True,upload_to='images')
    seller_name = models.ForeignKey(User,on_delete=models.CASCADE,default=2)



#addtocart
class Cart(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    @property
    def total_cost(self):
        return self.quantity * self.product.discounted_price

myapp/views.py
from email.mime import image
from itertools import product
from unicodedata import name
from myapp.models import Product
from cgitb import html
from multiprocessing import context
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.views.generic import ListView,TemplateView,DeleteView,CreateView,DetailView,UpdateView


 
# Create your views here.
def index(request):
    d = {
        "name":"Allu",
        "age":"24" ,
    }
    
    li = ["Allen","Sreerag","Alwin","Allu"]

    for i in range(0,10):
        print(i)

    context = {'names': li}

    return render(request, 'myapp/index.html',context=context)

def new_one(request):
    return render(request, 'listing/new_one.html')

class ProductListView(ListView):
    model = Product
    template_name = 'myapp/products.html'
    context_object_name = 'products'


@login_required
def products(request):
    # p = Product.objects.filter(price__gt =100000) 
    p = Product.objects.all()
    context = {'products':p}
    return  render(request, 'myapp/products.html',context=context)

def product_details(request,id):
    p = Product.objects.get(id=id)
    context = {'p':p}
    return render(request,'myapp/product_details.html',context=context)

class ProductDetailView(DetailView):
    model = Product
    template_name = 'myapp/product_details.html'
    context_object_name = 'p'

@login_required
def add_product(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        price = request.POST.get('price')
        desc = request.POST.get('desc')
        image = request.FILES['upload']
        p = Product(name=name,price=price,description=desc,image=image)
        p.seller_name = request.user
        p.save()

        return redirect('/myapp/products')

    return render(request,'myapp/add_product.html')

def update_product(request,id):
    p = Product.objects.get(id=id)
    context = {'p':p}
    if request.method == 'POST':
        p.name = request.POST.get('name')
        p.price = request.POST.get('price')
        p.description = request.POST.get('desc')

        try:
            p.image = request.FILES['upload']
        except:
            pass

        # p = Product(name=name,price=price,description=desc,image=image)
        p.save()

        return redirect('/myapp/products')
    
    return render(request,'myapp/update_product.html',context=context)

class ProductUpdateView(UpdateView):
    model = Product
    fields = ['name','price','description','image','seller_name']
    template_name ='myapp/update_product.html'
    context_object_name = 'p'
    success_url = reverse_lazy('myapp:products')


def delete_product(request,id):
    p = Product.objects.get(id=id)
    context = {'p':p}
    if request.method == 'POST':
        p.delete()
       

        return redirect('/myapp/products')
    
    return render(request,'myapp/delete_product.html',context=context)

class ProductDelete(DeleteView):
    model = Product
    template_name = 'myapp/delete_product.html'
    success_url = reverse_lazy('myapp:products')
    context_object_name = 'p'

#addtocart

def cart(request):
    context = {}
    return render(request,'myapp/cart.html',context)    

#addtocart
def add_to_cart(request):
    user = request.user
    product_id = request.GET.get('prod_id')
    product = product.objects.get(id = product_id)
    cart(user=user, product=product)
    return redirect('/cart')

def show_cart(request):
    user = request.user
    cart = Cartobjects.filter(user=user)
    return render(request,'myapp/add_to_cart.html',locals())

myapp/templates/myapp/add_product.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class="text-2xl font-bold m-10">Add Product</h1>
<form class="w-2/5 shadow-md m-10 p-10" method="POST" enctype="multipart/form-data">
{% csrf_token %}
<div class="mb-5">
    <label class="block text-grey-700 text-5m font-bold mb-2" for="">Product Name</label>
    <input class="appearance-none shadow border rounded-lg text-grey-800" placeholder=" Enter Product Name Here" type="text" name="name"
        id="name">
</div>
<div class="mb-5">
    <label class="block text-grey-700 text-5m font-bold mb-2" for="">Product Price</label>
    <input class="appearance-none shadow border rounded-lg text-grey-800" placeholder="Enter Product Price Here" type="text" name="price"
        id="price">
</div>
<div class="mb-5">
    <label class="block text-grey-700 text-5m font-bold mb-2" for="">Product Description</label>
    <input class="appearance-none shadow border rounded-lg text-grey-800" placeholder=" Enter Product Description Here" type="text" name="desc"
        id="desc">
</div>
<div class="mb-5">
    <label class="block text-grey-700 text-5m font-bold mb-2" for="">Product Image</label>
    <input type="file" name="upload" id="upload">
</div>
<div class="mb-5">

    <input
        class="focus:outline-none text-white bg-green-700 hover-bg-green-800 focus-ring-4 focus-ring-green-300 font-medium rounded-lg text-5m px-5 py-2.5 mr-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focusing-green-800"
        type="submit" accept="image/*" name="Add Product" value="Add Product">
</div>
</form>
{% endblock %}

myapp/templates/myapp/add_to_cart.html
{% extends 'myapp/base,html' %}
{% load static %}
{% block title %}Cart{% endblock title %}
{% block main-content %}
<div class="container my-5">

    <div class="row">
        {% if cart %}
        <h1 class="text-center mb-5">Shopping Cart</h1>
        <div class="col-sm-8">
            <div class="card">
                <div class="card-body">
                    <h3>Cart</h3>
                   { % for item in Cart %}
                   <div class="row">
                    <div class="col-sm-3 text-center align-self-center"><img src="{{item.product.product_image.url}}"  alt="" srcset="" class="img-fluid img-thumbnail shadow-sm" height="150" width="150"></div>
                    <div class="col-sm-9">
                        <div>
                            <h5>{{item.product.title}}</h5>
                            <p class="mb-2 text-muted small">{{item.product.description}}</p>
                            <div class="my-3">
                                <label for="quantity">Quantity:</label>
                                <a class="minus-cart btn" pid={{item.product.id}}><i class="fas fa-minus-square fa-lg"></i></a>
                                <span id="quantity">{{item.quantity}}</span>
                                <a class="plus-cart btn" pid={{item.product.id}}><i class="fas fa-plus-square fa-lg"></i></a>
                            </div>
                            <div class="d-flex justify-content-between">
                                <a href="#" class="remove-cart btn btn-sm btn-secondary mr-3" pid={{item.product.id}}>Remove Item</a>
                                <p class="mb-0"><span><strong>Rs.{{item.product.discounted_price}}</strong></span></p>
                            </div>
                        </div>
                    </div>
                   </div>
                   <hr class="text-muted">
                   {% endfor %}
                </div>
            </div>
        </div>

        <div class="col-sm-4">
            <div class="card">
                <div class="card-body">
                    <h3>The Total Amount of</h3>
                    <ul class="list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">Amount <span id="amount">Rs.{{amount}}</span></li>
                        <li class="list-group-item d-flex justify-content-between align-items-center px-0 ">Shipping <span>Rs. 40.00</span></li>
                        <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                            <div>
                                <strong>Total</strong><small>{including GST}</small>
                            </div>
                            <span id="totalamount"><strong>Rs.{{totalamount}}</strong></span>
                        </li>
                    </ul>
                    <div class="d-grid"><a href="{% url 'checkout' %}" class="btn btn-primary">Place Order </a></div>
                </div>
            </div>
        </div>
        {% else %}
        <h1 class="text-center mb-5">Cart Is Empty</h1>
        {% endif %}
    </div>
</div>

{% endblock main-content %}

myapp/templates/myapp/base.html
{% load static tailwind_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% tailwind_css %}
</head>
<body>
    <section>
        <div class="navbar bg-base-100 drop-shadow-md">
            <div class="flex-1">
              <a class="btn btn-ghost normal-case text-xl">MySite Cart</a>
            </div>
            <div class="flex-none">
              <div class="dropdown dropdown-end">
                <label tabindex="0" class="btn btn-ghost btn-circle">
                  <div class="indicator">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                      stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
                    </svg>
                    <span class="badge badge-sm indicator-item">8</span>
                  </div>
                </label>
                <div tabindex="0" class="mt-3 card card-compact dropdown-content w-52 bg-base-100 shadow">
                  <div class="card-body">
                    <span class="font-bold text-lg">8 Items</span>
                    <span class="text-info">Subtotal: $999</span>
                    <div class="card-actions">
                      <button class="btn btn-primary btn-block">View cart</button>
                    </div>
                  </div>
                </div>
              </div>
              <div class="dropdown dropdown-end z-10">
                <label tabindex="0" class="btn btn-ghost btn-circle avatar">
                  <div class="w-10 rounded-full">
                    <img src="https://placeimg.com/80/80/people" />
                  </div>
                </label>
                <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
                  <li>
                    <a class="justify-between">
                      Profile
                      <span class="badge">New</span>
                    </a>
                  </li>
                  <li><a>Settings</a></li>
                  {% if user.is_authenticated  %}
                  <li><a href="{% url 'users:logout' %}">Logout</a></li>
                  {% else %} 
                  <li><a href="{% url 'users:login' %}">Login</a></li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </div>
        </section>
    
    {% block content %}
    
    {% endblock  %}
</body>
</html>

myapp/templates/myapp/cart.html
<h3>Cart</h3>

myapp/templates/myapp/delete_product.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class="text-2xl font-bold m-10">Delete Product</h1>
<form class="w-2/5 shadow-md m-10 p-10" method="POST" enctype="multipart/form-data">
{% csrf_token %}
<div class="mb-5">
    <label class="block text-grey-700 text-5m font-bold mb-2" for="">Product Name : {{p.name}}</label>
    
</div>
<div class="mb-5">
    <label class="block text-grey-700 text-5m font-bold mb-2" for="">Product Price : {{p.price}}</label>
    
</div>
<div class="mb-5">
    <label class="block text-grey-700 text-5m font-bold mb-2" for="">Product Description : {{p.description}}</label>
    
</div>
<div class="mb-5">
    <label class="block text-grey-700 text-5m font-bold mb-2" for="">Product Image</label>
    <img class = "w-36 mb-3 rounded-lg" src="{{p.image.url}}" alt = "Image Not Found">
    
</div>
<div class="mb-5">

    <input
        class="focus:outline-none text-white bg-green-700 hover-bg-green-800 focus-ring-4 focus-ring-green-300 font-medium rounded-lg text-5m px-5 py-2.5 mr-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focusing-green-800"
        type="submit" accept="image/*" name="Add Product" value="Delete Product">
</div>
</form>
{% endblock %}

myapp/templates/myapp/index.html
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 style = "color: navy;"> Hello MyApp</h1>
    <ol>
    {% for n in names %}
       <li> <h1 style="color: darkred;">{{n}}</h1></li>
    {% endfor %}
</ol>
</body>
</html>

myapp/templates/myapp/product_details.html
{% extends "myapp/base.html" %}

{% block content %}

<!-- <div class="card">
        <img src="{{p.image.url}}" alt="Image Not Found" style="width:200px">
        <h1>{{p.name}}</h1>
        <p class="price">₹ {{p.price}}</p>
        <p>{{p.description}}</p>
        <br>
        <br>
        
    </div> -->

<div class="flex p-10 w-full h-200 bg-purple-50">
    <img class="w-1/3 rounded-xl" src="{{p.image.url}}" alt="Unable to Load Image">
    <div class="2/3 text-xl ml-10 front-semibold">
        <div class="mt-10 text-sky-700">ID : {{p.id}}</div>
        <div class="mt-10 text-blue-400">Name : {{p.name}}</div>
        <div class="mt-10 text-pink-400">Description : {{p.description}}</div>
        <div class="mt-10 text-green-400">Price: {{p.price}}</div><br>
        <div class="mt-10 text-green-400">Sold By: {{p.seller_name}}</div><br>
        <a href="{ url 'users:sellerprofile' p.seller_name.id %}">
            <div class="text-sm text-stone-500 ">Seller Details</div>
        </a>

        <br>
        <div class="buttons row flex" style="font-family: Rajdhani;">
            <form action="/add_to-cart" class="d-inline">
            <button type="submit"
                class="d-grid gap-2 btn1 btn btn-danger p-1 m-1 btn-lg text-decoration-none text-while">Add to
                cart</button> 
            </form>
            
            <!-- <div class="btn btn-dark p-1 my-5 btn-lg"> <a href="a" class="text-decoration-none text-white">Buy Now</a>
            </div> -->
        </div>
    </div>
</div>
{% endblock %}

myapp/templates/myapp/products.html
{% extends "myapp/base.html"  %}

 {% block content %}



  <div class="container items-center justify-center mx-auto px-4 grid grid-cols-2 grid-flow-row gap-5 p-5 z-30 place-content-center ">



    {% for p in products %}

    <div class="card w-96 glass ">
      <figure><img class="object-cover h-60 w-90" src="{{p.image.url}}" alt="Something Went Wrong!" /></figure>
      <div class="card-body">
        <h2 class="card-title">{{p.name}}</h2>
        <p>{{p.description}}</p>
        <div class="card-actions justify-end">
          <a href="{% url 'myapp:product_details' p.id %}">
          <button class="btn btn-primary">₹{{p.price}}</button>
        </a>
        
        </div>
      </div>
    </div>

    {% comment %} <div class="box-content h-64 w-32 p-4 border-4 rounded-xl ">
      <h2 style="text-align:center">Product Card</h2>
      <a href="{% url 'product_details' p.id %}">
        <div class="card">
          <img src="{{p.image.url}}" alt="Image Not Found" style="width:200px">
          <h1 text-sky-500>{{p.name}}</h1>
          <p class="price">₹ {{p.price}}</p>
          <p>{{p.description}}</p>
          <br>
          <br>

        </div>
      </a>

    </div> {% endcomment %}
    {% endfor %}
  </div>

 
  {% endblock  %}

myapp/templates/myapp/update_product.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class="text-2xl font-bold m-10"> Add Product</h1>
<form class="w-2/5 shadow-md m-10 p-10" method="POST" enctype="multipart/form-data">
{% csrf_token %}
<div class="mb-5">
    <label class="block text-grey-700 text-5m font-bold mb-2" for="">Product Name</label>
    <input class="appearance-none shadow border rounded-lg text-grey-800" value="{{p.name}}" placeholder=" Enter Product Name Here" type="text" name="name"
        id="name">
</div>
<div class="mb-5">
    <label class="block text-grey-700 text-5m font-bold mb-2" for="">Product Price</label>
    <input class="appearance-none shadow border rounded-lg text-grey-800" value="{{p.price}}" placeholder="Enter Product Price Here" type="text" name="price"
        id="price">
</div>
<div class="mb-5">
    <label class="block text-grey-700 text-5m font-bold mb-2" for="">Product Description</label>
    <input class="appearance-none shadow border rounded-lg text-grey-800" value = "{{p.description}}" placeholder=" Enter Product Description Here" type="text" name="desc"
        id="desc">
</div>
<div class="mb-5">
    <label class="block text-grey-700 text-5m font-bold mb-2" for="">Product Image</label>
    <img class = "w-36 mb-3 rounded-lg" src="{{p.image.url}}" alt = "Image Not Found">
    <input type="file" name="upload" id="upload">
</div>
<div class="mb-5">

    <input
        class="focus:outline-none text-white bg-green-700 hover-bg-green-800 focus-ring-4 focus-ring-green-300 font-medium rounded-lg text-5m px-5 py-2.5 mr-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focusing-green-800"
        type="submit" accept="image/*" name="Add Product" value="Update Product">
</div>
</form>
{% endblock %}